name: Domain Expiration Monitor

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:
    inputs:
      threshold:
        description: "Days before expiration to trigger an alert"
        required: false
        default: "30"

permissions:
  issues: write
  contents: read

jobs:
  check-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run domain check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          DAYS_THRESHOLD: ${{ github.event.inputs.threshold || '30' }}
        run: python check_domains.py
